### ISSUE TITLE
NatNet 2 support

### ISSUE THREAD

**Issue by omardarwish1995** [mje-nz/natnet_ros#3]
I get the following error when I run "rosrun natnet_ros client _server:=10.195.79.98":

_```
radlab@DESKTOP-TSTVI8U:~/catkin_ws$ rosrun natnet_ros client _server:=10.195.79.98
[INFO] [1551755108.133212]: Connecting to 10.195.79.98
Traceback (most recent call last):
  File "/home/radlab/catkin_ws/src/natnet_ros/natnet_ros/scripts/client", line 217, in <module>
    node.run()
  File "/home/radlab/catkin_ws/src/natnet_ros/natnet_ros/scripts/client", line 207, in run
    client = natnet.Client.connect(server, logger=self.log)
  File "/home/radlab/catkin_ws/src/natnet_ros/python_natnet/python_natnet/src/natnet/comms.py", line 415, in connect
    return cls._simple_connect(server, logger, timeout)
  File "/home/radlab/catkin_ws/src/natnet_ros/python_natnet/python_natnet/src/natnet/comms.py", line 393, in _simple_connect
    timeout=timeout)
  File "/home/radlab/catkin_ws/src/natnet_ros/python_natnet/python_natnet/src/natnet/comms.py", line 154, in wait_for_message_with_id
    return protocol.deserialize_payload(message_id, payload), received_time
  File "/home/radlab/catkin_ws/src/natnet_ros/python_natnet/python_natnet/src/natnet/protocol/common.py", line 271, in deserialize_payload
    return _registry.deserialize_payload(*args, **kwargs)
  File "/home/radlab/catkin_ws/src/natnet_ros/python_natnet/python_natnet/src/natnet/protocol/common.py", line 221, in deserialize_payload
    message = message_type.deserialize(payload_data, version)
  File "/home/radlab/catkin_ws/src/natnet_ros/python_natnet/python_natnet/src/natnet/protocol/ServerInfoMessage.py", line 67, in deserialize
    high_resolution_clock_frequency = data.unpack(uint64_t)
  File "/home/radlab/catkin_ws/src/natnet_ros/python_natnet/python_natnet/src/natnet/protocol/common.py", line 92, in unpack
    value = struct_type.unpack(self.data[self.offset:self.offset + struct_type.size])
struct.error: unpack requires a string argument of length 8
```_

Motive Version: 1.10.3
ROS Version: Kinetic
Ubuntu: 16.04
Python: 2.7.12

Note: It works when using the fake client and crashes when I enter the Motive IP Address

Thanks in advance!

**Comment by mje-nz** [comment]
Thanks for letting me know!

Unfortunately I don't have access to a Motive version that old, so I don't have any test data for the old protocol. If you give me a packet capture of another NatNet client successfully communicating with your version of Motive I'll put it on my to-do list.

**Comment by omardarwish1995** [comment]
![Win_Data](https://user-images.githubusercontent.com/44329003/54169625-810a2700-4441-11e9-8caa-aaeb56ac56c9.PNG)

We were able to get it working with Natnet 2.10. The attached data was captured after we ran the "WinFormTestApp.exe" in the NatnetSDK samples.

Is that what you were asking for or do you need more information?

**Comment by mje-nz** [comment]
Nice work. What I need is a recording of your raw network traffic, captured with a network sniffing tool like [Wireshark](https://www.wireshark.org). 

First, start the capture with the filter "port 1510 or port 1511" so you only include NatNet traffic.
<img width="805" alt="Screen Shot 2019-03-12 at 3 28 49 PM" src="https://user-images.githubusercontent.com/6166539/54170429-92a00d00-44db-11e9-893f-7c8d14281a6c.png">

Then, open WinFormTestApp.exe and do whatever you did to get it going. You should see packets appearing in Wireshark. Give it a few seconds, then stop capturing in Wireshark, save the capture file, and upload it here.

It would be ideal if you could run WinFormTestApp.exe on a different computer to Motive, but if you can't then I can probably still figure out what's going on.

**Comment by omardarwish1995** [comment]
[WireSharkData.zip](https://github.com/mje-nz/natnet_ros/files/2959288/WireSharkData.zip)

Thank you for your reply. Unfortunately we were not able to run it on two separate machines. 

Please see attached the captured data requested

**Comment by mje-nz** [comment]
That's great, thanks! The error you reported is in the skeleton parsing code, which I've never been able to test as we only use our mocap for robots. The packet format doesn't seem to be what NaturalPoint says it is, would you mind collecting a little more data for me?

Open a command prompt in the NatNet SDK samples folder. Start the capture in Wireshark as before. Run SampleClient.exe in the command prompt, press 1 to connect, wait a few seconds while data flashes past, then press q to quit. It should look something like this:
![Capture](https://user-images.githubusercontent.com/6166539/54252086-59849d00-45ae-11e9-9725-09f01e29b912.PNG)

Select all the output (Ctrl-A), copy it (Enter), and attach it here along with the capture file.

**Comment by omardarwish1995** [comment]
Please see attached the captured data and the SampleData.exe data

Thank you,

[WireShark_03-13-2018.zip](https://github.com/mje-nz/natnet_ros/files/2964474/WireShark_03-13-2018.zip)

**Comment by mje-nz** [comment]
That's perfect, thanks again.

I've made some changes in the `dev` branch which should fix your issue. Please try it out and let me know how it goes. Depending on your git config you might have to run `git submodule update` when you change branches.

At the moment I have each bone in the skeleton published as a `PoseStamped`. What do you want to be able to do with the data? I'm open to suggestions for how to represent it.

**Comment by omardarwish1995** [comment]
Thank you very much. Unfortunately we get a new error (please see attached.)

and to answer your question, we are trying to capture live stream data and create a live stream simulation. 

Thanks in advance
![Capture](https://user-images.githubusercontent.com/44329003/54400309-329e9780-4690-11e9-84c1-37a858b292e2.PNG)

**Comment by mje-nz** [comment]
Okay, that's an issue with connecting to old versions of Motive. It should be fixed now, please update (`git pull` and `git submodule update`) and try again.

**Comment by omardarwish1995** [comment]
Hi, 
We tried the updated library and ran into a similar error as seen in the attached screenshot. As you can see, we are using the right data port and multicast address. Even when we tried to use an IP address instead of setting Motive to loopback, we got the same exact error. Any help fixing this would be appreciated! 

![Capture_31519](https://user-images.githubusercontent.com/44329003/54449164-78ed0880-471b-11e9-902c-acfe46099651.PNG)

**Comment by mje-nz** [comment]
You have to be in src/natnet_ros when you run git pull and git submodule
update or they won’t do anything ;)

**Comment by omardarwish1995** [comment]
Hi Matthew,
Sorry for not replying earlier as we were on spring break and had no access to the mocap system.

I tried your suggestion in the previous comment and it still gave me the same error as attached.

Is it because the program is using "multicast_address" while it is labeled "Multicast Interface" in the motive application?

Please advise.

![capture_32519](https://user-images.githubusercontent.com/44329003/54928367-c7e82a00-4ee1-11e9-8a4f-876efc33dc88.PNG)

**Comment by mje-nz** [comment]
Ah I see the problem, try again now.

**Comment by mje-nz** [comment]
Hi Omar, have you had a chance to test these changes?

**Comment by omardarwish1995** [comment]
Hi Matthew,

We tried out the update and still ran into errors. It seems too tedious of a process to force the library to work with an older version so after speaking with senior members of our lab, we have decided to update our Motive software to the latest version (2.1). 
The  purpose of our project is to live stream data from Motive in order to create simulations of the human motions and  eventually control robots. My teammates and I would like to acknowledge your work and your assistance to us in our paper. Is there a certain affiliation that you would  like us to recognize? 

Again,  we are immensely thankful for your help. I will keep  you in the loop once we get our updated software and test your library.

Best,
Omar

**Comment by mje-nz** [comment]
Sorry Omar, I missed this one! If it's not too late, my affiliation is Electrical and Computer Engineering, University of Canterbury, New Zealand. I'd be interested to see your paper if you don't mind sharing.

How are you getting on with updating Motive?
