### ISSUE TITLE
Logging error on Melodic

### ISSUE THREAD

**Issue by mje-nz** [mje-nz/natnet_ros#5]
To reproduce:
```
$ docker run --rm -it -v $(pwd):/work/src/natnet_ros -w /work ros:melodic-perception bash
# catkin_make
# . devel/setup.bash
# roscore &
# rosrun natnet_ros client
Traceback (most recent call last):
  File "/work/src/natnet_ros/natnet_ros/scripts/client", line 278, in <module>
    node.run()
  File "/work/src/natnet_ros/natnet_ros/scripts/client", line 268, in run
    client = natnet.Client.connect(server, logger=self.log)
  File "/work/src/natnet_ros/python_natnet/python_natnet/src/natnet/comms.py", line 435, in connect
    return cls._discover_and_connect(logger, timeout)
  File "/work/src/natnet_ros/python_natnet/python_natnet/src/natnet/comms.py", line 371, in _discover_and_connect
    logger.info('Discovering servers')
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/core.py", line 194, in loginfo
    _base_logger(msg, *args, logger_level='info', **kwargs)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/core.py", line 187, in _base_logger
    logfunc(msg, *args)
  File "/usr/lib/python2.7/logging/__init__.py", line 1174, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1293, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1303, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1343, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 766, in handle
    self.emit(record)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/roslogging.py", line 239, in emit
    record_message = _defaultFormatter.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
```

**Comment by mje-nz** [comment]
(fixed in dev)
