### ISSUE TITLE
UnboundLocalError: local variable 'm' referenced before assignment

### ISSUE THREAD

**Issue by knightsamar** [mje-nz/natnet_ros#8]
ROS: Kinetic on Ubuntu 16.04.5
Python: 2.7.12
Motive: 2.1.1 (43799)
Streaming settings for Motive: multicast, with local interface set to the same network as ROS 
Firewall turned off on both machines.

I see the "_Network client connection request received_" and "_Network client model request received_" messages on Motive so the connection is definitely successful between both machines but it seems like there is problem in getting and/or putting data in the topics.

On a sidenote, just testing using python-natnet (at the same commit as your submodule), gets me to "_Getting data descriptions_" followed by a "_Ready_" so I wonder if it's just a problem with putting data in the topics.

```
charisma@charisma-predator1:~/natnet_ros$ rosrun natnet_ros client _server:=192.168.1.196
[INFO] [1566247540.970316]: Connecting to 192.168.1.196
[INFO] [1566247547.665578]: Ready
/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py:842: UserWarning: '~rigid_bodies/ground_plane_b.../pose' is not a legal ROS graph resource name. This may cause problems with other ROS tools
  super(Publisher, self).__init__(name, data_class, Registration.PUB)
/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py:842: UserWarning: '~rigid_bodies/ground_plane_b.../markers' is not a legal ROS graph resource name. This may cause problems with other ROS tools
  super(Publisher, self).__init__(name, data_class, Registration.PUB)
/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py:842: UserWarning: '~rigid_bodies/ground_plane_b.../marker1' is not a legal ROS graph resource name. This may cause problems with other ROS tools
  super(Publisher, self).__init__(name, data_class, Registration.PUB)
/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py:842: UserWarning: '~rigid_bodies/ground_plane_b.../marker2' is not a legal ROS graph resource name. This may cause problems with other ROS tools
  super(Publisher, self).__init__(name, data_class, Registration.PUB)
/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py:842: UserWarning: '~rigid_bodies/ground_plane_b.../marker3' is not a legal ROS graph resource name. This may cause problems with other ROS tools
  super(Publisher, self).__init__(name, data_class, Registration.PUB)
Traceback (most recent call last):
  File "/home/charisma/catkin_ws/src/natnet_ros/natnet_ros/scripts/client", line 224, in <module>
    node.run()
  File "/home/charisma/catkin_ws/src/natnet_ros/natnet_ros/scripts/client", line 210, in run
    client.spin()
  File "/usr/local/lib/python2.7/dist-packages/natnet-0.1.0-py2.7.egg/natnet/comms.py", line 500, in spin
    self.run_once(timeout)
  File "/usr/local/lib/python2.7/dist-packages/natnet-0.1.0-py2.7.egg/natnet/comms.py", line 480, in run_once
    self._callback(rigid_bodies, labelled_markers, timestamp_and_latency)
  File "/home/charisma/catkin_ws/src/natnet_ros/natnet_ros/scripts/client", line 184, in mocap_frame_callback
    self._publish_marker_points(header, markers)
  File "/home/charisma/catkin_ws/src/natnet_ros/natnet_ros/scripts/client", line 168, in _publish_marker_points
    leftovers_msg.ids.append(m.marker_id)
UnboundLocalError: local variable 'm' referenced before assignment

```
I am willing to help in testing and maybe try out making changes to the code to fix this if you can help point me out in the right direction :)

Thank you for building and maintaining this!

**Comment by mje-nz** [comment]
Thanks for the bug report! This looks familiar, could you please check out the `dev` branch and see if it's fixed there?

**Comment by knightsamar** [comment]
On **dev** branch with all the same settings and systems, I get:

```
charisma@charisma-predator1:~/catkin_ws$ rosrun natnet_ros client _server:=192.168.1.196
[INFO] [1566256568.133406]: Connecting to 192.168.1.196
[INFO] [1566256576.274806]: Ready
/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py:842: UserWarning: '~rigid_bodies/ground_plane_b.../pose' is not a legal ROS graph resource name. This may cause problems with other ROS tools
  super(Publisher, self).__init__(name, data_class, Registration.PUB)
/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py:842: UserWarning: '~rigid_bodies/ground_plane_b.../markers' is not a legal ROS graph resource name. This may cause problems with other ROS tools
  super(Publisher, self).__init__(name, data_class, Registration.PUB)
/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py:842: UserWarning: '~rigid_bodies/ground_plane_b.../marker1' is not a legal ROS graph resource name. This may cause problems with other ROS tools
  super(Publisher, self).__init__(name, data_class, Registration.PUB)
/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py:842: UserWarning: '~rigid_bodies/ground_plane_b.../marker2' is not a legal ROS graph resource name. This may cause problems with other ROS tools
  super(Publisher, self).__init__(name, data_class, Registration.PUB)
/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py:842: UserWarning: '~rigid_bodies/ground_plane_b.../marker3' is not a legal ROS graph resource name. This may cause problems with other ROS tools
  super(Publisher, self).__init__(name, data_class, Registration.PUB)
Traceback (most recent call last):
  File "/home/charisma/catkin_ws/src/natnet_ros/natnet_ros/scripts/client", line 29, in <module>
    node.run()
  File "<string>", line 280, in run
  File "/usr/local/lib/python2.7/dist-packages/natnet-0.1.0-py2.7.egg/natnet/comms.py", line 500, in spin
    self.run_once(timeout)
  File "/usr/local/lib/python2.7/dist-packages/natnet-0.1.0-py2.7.egg/natnet/comms.py", line 480, in run_once
    self._callback(rigid_bodies, labelled_markers, timestamp_and_latency)
TypeError: mocap_frame_callback() takes exactly 5 arguments (4 given)
```
I have tried with having the **python_natnet** submodule on dev as well as master branch with the same results.

**Comment by mje-nz** [comment]
When you change branch you need to run `git submodule update` so you get the correct submodule commit.

**Comment by knightsamar** [comment]
Thanks. That seems to change things a bit but not exactly how we expected:

I got it to run randomly and reach "Ready" once but it didn't publish any data in the rostopics ``/mocap/markers/vis`` or ``/mocap/markers/leftovers``. I tested using ``rostopic echo``. It just kept on running without any output.

But after that one run it keeps on randomly crashing with the following error:

```
charisma@charisma-predator1:~/catkin_ws/src/natnet_ros$ rosrun natnet_ros client _server:=192.168.1.196
[INFO] [1566342378.982381]: Connecting to 192.168.1.196
[INFO] [1566342394.644415]: Ready
Traceback (most recent call last):
  File "/home/charisma/catkin_ws/src/natnet_ros/natnet_ros/scripts/client", line 29, in <module>
    node.run()
  File "<string>", line 280, in run
  File "/usr/local/lib/python2.7/dist-packages/natnet-0.1.0-py2.7.egg/natnet/comms.py", line 500, in spin
    self.run_once(timeout)
  File "/usr/local/lib/python2.7/dist-packages/natnet-0.1.0-py2.7.egg/natnet/comms.py", line 480, in run_once
    self._callback(rigid_bodies, labelled_markers, timestamp_and_latency)
TypeError: mocap_frame_callback() takes exactly 5 arguments (4 given)
```

I am unable to figure out what could lead to this. Any hints?

**Comment by mje-nz** [comment]
The `mocap_frame_callback() takes exactly 5 arguments (4 given)` error is almost certainly from having the wrong `python_natnet` submodule version. It looks like you might have `catkin_make install`ed the old version, `catkin_make`ed the new version, and sourced the wrong `setup.bash`, or something along those lines.

**Comment by knightsamar** [comment]
Sorry for the delay in getting back. That indeed worked! But now I am running into a new problem for which I will report a new issue. 

Closing this as resolved with `dev` branch.
